---
title: "dataproject"
author: "khatia kilanava"
date: "December 27, 2017"
output: html_document
---

```{r}
library(dplyr)
```


```{r}
original <- read.csv("C://Users//khatia//Desktop//dataminingpro//market_price.csv")
```

```{r}
head(original,2)
```

```{r}
nrow(original)
ncol(original)
str(original)
```

filtering the currencies not equal to euros
```{r}
original<-filter(original, currency=="EUR")
original<-filter(original,currency!="")
```


```{r}
nrow(original)
```
previously we had 19528358 rows, now it's 18544211

```{r}
original<-as.data.frame(original)
head(original,5)
```

now filtering unimportant rows like : id, broker_location_code, rc_location_code, excess_included:
```{r}
original<-original[, !(colnames(original) %in% c("broker_location_code","rc_location_code","excess_included", "source","broker","source_country", "supplier_name","currency"))]
```

changing empty values in NA 
```{r}
original<-original$model_name[original$model_name==""]<-NA
```

filtering NA values
```{r}
original<-na.omit(original)
```

cleaning capitalization errors

```{r}
original$transmission[original$transmission=="AUTOMATIC"]<-"automatic"
original$transmission[original$transmission=="MANUAL"]<-"manual"

```










